### ISSUE TITLE
g++でビルドできるようにする

### ISSUE THREAD

**Issue by 200km** [ut-issl/s2e-user-for-c2a-core#19]
## 概要
g++でビルドできるようにする

## 詳細
現時点で、`USE_SCI_COM_WINGS`をOFFにすればコンパイルは通るが、リンカエラーが出る。  

## close条件
g++でビルドできるようになる

## 備考
NA

## 注意
NA

**Comment by sksat** [comment]
これでビルドできそう
- https://github.com/ut-issl/c2a-core/pull/330
